In [2]:
import pandas as pd
import os
import saspy
# starting sas session
sas = saspy.SASsession(
# own pathway to your Java 7 or 8 file on
java='C:\\Program Files (x86)\\Java\\jre-1.8\\bin\\java.exe',
#European Home Region 1
iomhost=['odaws01-euw1.oda.sas.com','odaws02-euw1.oda.sas.com'],
iomport= 8591,
authkey= 'oda',
encoding ='utf-8')
sas

#observed variance structure
xior = pd.read_csv("C:/Users/katri/Documents/Python_scripts/MDA_project/Modern-Data-Analytics-Backend/Dataset/train/train_night_xior.csv")
python_object = sas.df2sd(xior, 'xior', libref='WORK')

##sas code (ANCOVA)
variance_structure_code = """
data xior;
set xior;
hourclass = night_hour;
run;

proc mixed data=xior;
class Date weekday downseason hourclass;
model laeq=night_hour  night_hour_sq night_hour_cu  
	downseason night_hour*downseason night_hour_sq*downseason night_hour_cu*downseason 
	weekday night_hour*weekday night_hour_sq*weekday night_hour_cu*weekday
	downseason*weekday night_hour*downseason*weekday night_hour_sq*downseason*weekday night_hour_cu*downseason*weekday
	
	LC_HUMIDITY night_hour*LC_HUMIDITY night_hour_sq*LC_HUMIDITY night_hour_cu*LC_HUMIDITY
	LC_DWPTEMP night_hour*LC_DWPTEMP night_hour_sq*LC_DWPTEMP night_hour_cu*LC_DWPTEMP
	LC_WINDSPEED night_hour*LC_WINDSPEED night_hour_sq*LC_WINDSPEED night_hour_cu*LC_WINDSPEED
	
	Total_Event_Score night_hour*Total_Event_Score night_hour_sq*Total_Event_Score night_hour_cu*Total_Event_Score;
repeated hourclass / subject=Date type=un r ;
run;
"""
variance_structure = sas.submitLST(variance_structure_code)

sas.endsas

# the variance can be read from the variance-covariance table. The column represent the different time points. The shape of the observed variance can be seen when plotting the variances against the time points.

Using SAS Config named: default
SAS Connection established. Subprocess id is 6488

<bound method SASsession.endsas of Access Method         = IOM
SAS Config name       = default
SAS Config file       = c:\Users\katri\Documents\Python_scripts\MDA_project\Modern-Data-Analytics-Backend\.venv\lib\site-packages\saspy\sascfg.py
WORK Path             = /saswork/SAS_work7DD7000064D7_odaws01-euw1.oda.sas.com/SAS_work2C3D000064D7_odaws01-euw1.oda.sas.com/
SAS Version           = 9.04.01M7P08062020
SASPy Version         = 5.1.2
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = utf-8
Python Encoding value = utf-8
SAS process Pid value = 25815

>